--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- name: Install WSO2 DSS
  hosts: '{{ hosts | default("DSS") }}'
  user: root
  roles:
    - common
    - java
    - certs
