--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- name: Install WSO2 DSS
  hosts: '{{ hosts | default("DSS") }}'
  user: root
  roles:
    - common
    - java
    - dss
  vars:
    patches: 
      - { "No" : "0012", "CarbonVersion" : "4.4.0" }
      - { "No" : "0016", "CarbonVersion" : "4.4.0" }
      - { "No" : "0027", "CarbonVersion" : "4.4.0" }
      - { "No" : "0042", "CarbonVersion" : "4.4.0" }