--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#--------------------------------------------

- include: install.yml
- include: keystore.yml