--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- name: Generate self-signed certificate
  command: 'openssl req -x509 -nodes -newkey rsa:2048 -subj "/C=MD/L=Chisinau/O=EGC/CN={{ HostName }}" -days 73000 -keyout "{{ WSO2FileRepository }}{{ HostName }}.key" -out "{{ WSO2FileRepository }}{{ HostName }}.crt"'

- name: Convert to PKCS12 certificate
  command: 'openssl pkcs12 -export -in "{{ WSO2FileRepository }}{{ HostName }}.crt" -inkey "{{ WSO2FileRepository }}{{ HostName }}.key" -out "{{ WSO2FileRepository }}{{ HostName }}.p12" -passout "pass:{{ KeyStorePassword }}" -name "{{ KeyStoreKeyAlias }}"'

- name: Convert PKCS12 to JKS
  command: 'keytool -importkeystore -srckeystore "{{ WSO2FileRepository }}{{ HostName }}.p12" -srcstoretype PKCS12 -srcstorepass "{{ KeyStorePassword }}" -destkeystore "{{ WSO2FileRepository }}wso2carbon.jks" -deststorepass "{{ KeyStorePassword }}" -destkeypass "{{ KeyStoreKeyPassword }}" -alias "{{ KeyStoreKeyAlias }}"'
