--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- name: Add apt-repository
  apt_repository: repo="ppa:webupd8team/java" state=present
    
- name: Automatically accept Oracle license
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: Install Java 8
  apt: name=oracle-java8-installer state=latest install_recommends=yes update_cache=yes
      
- name: Set Java 8 Env
  apt: name=oracle-java8-set-default state=latest install_recommends=yes