--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- apt: name=ntpdate state=present

- apt: name=ntp state=present

- service: name=ntp state=started enabled=yes

- apt: name=openssl state=present

- apt: name=unzip state=present

# WSO2 Specific

- name: Create service group
  group: name={{ WSO2Group }} state=present

- name: Create service user
  user: name={{ WSO2Owner }} state=present shell=/bin/bash group={{ WSO2Group }} system=yes
  
- name: Create directories
  file: path={{ WSO2FileRepository }} owner={{ WSO2Owner }} group={{ WSO2Group }} state=directory
  
# Generate certificate

- name: Generate certificate
  command: 'openssl req -new -nodes -x509 -subj /C=MD/ST=Chisinau/L=Chisinau/O=EGC/CN={{ HostName }} -days 73000 -keyout {{ WSO2FileRepository }}{{ HostName }}.key -out {{ WSO2FileRepository }}{{ HostName }}.crt -extensions v3_ca creates={{ WSO2FileRepository }}{{ HostName }}.crt'