--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- name: Ensure required packages are installed
  apt: name="{{ item }}" state=present
  with_items:
    - ntpdate
    - ntp
    - openssl
    - unzip

- name: Ensure ntp is started
  service: name=ntp state=started enabled=yes

# WSO2 Specific

- name: Create service group
  group: name={{ WSO2Group }} state=present

- name: Create service user
  user: name={{ WSO2Owner }} state=present shell=/bin/bash group={{ WSO2Group }} system=yes
  
- name: Create file repository
  file: path={{ WSO2FileRepository }} owner={{ WSO2Owner }} group={{ WSO2Group }} state=directory