--- 
#---------------------------------------------# 
# MConnect - Centrul de Guvernare Electronica #
#---------------------------------------------#

- apt: name=ntpdate state=present

- apt: name=ntp state=present

- service: name=ntp state=started enabled=yes

- apt: name=openssl state=present

- apt: name=unzip state=present
